export const types = {
    SET_CURRENT_STEP: 'SET_CURRENT_STEP',
    SET_LOADING: 'SET_LOADING',
    SET_CATEGORIES: 'SET_CATEGORIES',
    SET_CATEGORY: 'SET_CATEGORY',
    SET_BASIC_INFO: 'SET_BASIC_INFO',
    SET_IMAGE: 'SET_IMAGE',
    SET_STORY: 'SET_STORY',
    SET_ADDRESS: 'SET_ADDRESS',
    SET_BANK_ACCOUNT: 'SET_BANK_ACCOUNT',
};