export const types = {
    SET_CURRENT_STEP: 'SET_CURRENT_STEP',
    SET_STEPS_DONE: 'SET_STEPS_DONE',
    SET_LOADING: 'SET_LOADING',
    SET_CATEGORIES: 'SET_CATEGORIES',
    SET_CATEGORY: 'SET_CATEGORY',
    SET_BASIC_INFO: 'SET_BASIC_INFO',
    SET_IMAGE: 'SET_IMAGE',
    SET_STORY: 'SET_STORY',
    GET_AUTHORIZED_USER: 'GET_AUTHORIZED_USER',
    SET_AUTHORIZED_USER: 'SET_AUTHORIZED_USER',
    SET_ADDRESS: 'SET_ADDRESS',
    SET_BANK_ACCOUNT: 'SET_BANK_ACCOUNT',
    SET_DETAILS: 'SET_DETAILS'
};